"use client";
import { useCallback, useEffect, useState } from "react";
import { Button, Card, DatePicker, Drawer, Form, Input, message, Select, Space, Table, Tag } from "antd";
import { DownloadOutlined, PlusOutlined } from "@ant-design/icons";
import dayjs from "dayjs";
type Dept={id:number;name:string}; type Session={id:number;title:string;startTime:string;endTime:string;departmentIds:string}; type Emp={id:number;name:string;employeeNo?:string;department:{name:string};record?:{status:string;remark?:string}|null};
const labels:Record<string,string>={pending:"待过堂",passed:"通过",failed:"未通过",leave:"请假"}; const colors:Record<string,string>={pending:"default",passed:"success",failed:"error",leave:"blue"};
export default function Page(){const[sessions,setSessions]=useState<Session[]>([]),[depts,setDepts]=useState<Dept[]>([]),[sessionId,setSessionId]=useState<number>(),[deptId,setDeptId]=useState<number>(),[search,setSearch]=useState(""),[rows,setRows]=useState<Emp[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false);const[form]=Form.useForm();
const loadSessions=async()=>{const[a,b]=await Promise.all([fetch("/api/passage-sessions").then(r=>r.json()),fetch("/api/departments").then(r=>r.json())]);if(a.success){setSessions(a.data);if(!sessionId&&a.data[0])setSessionId(a.data[0].id)}if(b.success)setDepts(b.data)};useEffect(()=>{void loadSessions()},[]);
const load=useCallback(async()=>{if(!sessionId)return;setLoading(true);try{const p=new URLSearchParams({sessionId:String(sessionId)});if(deptId)p.set("departmentId",String(deptId));const d=await fetch(`/api/passage-records?${p}`).then(r=>r.json());if(d.success)setRows(d.data);else message.error(d.message)}finally{setLoading(false)}},[sessionId,deptId]);useEffect(()=>{void load()},[load]);
const save=async(id:number,status:string,remark?:string)=>{const d=await fetch("/api/passage-records",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,employeeId:id,status,remark})}).then(r=>r.json());if(!d.success)return message.error(d.message);setRows(v=>v.map(x=>x.id===id?{...x,record:{status,remark}}:x))};
const create=async()=>{const v=await form.validateFields();const d=await fetch("/api/passage-sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...v,startTime:v.range[0].toISOString(),endTime:v.range[1].toISOString()})}).then(r=>r.json());if(!d.success)return message.error(d.message);message.success("过堂场次已创建");setOpen(false);form.resetFields();await loadSessions();setSessionId(d.data.id)};
const filtered=rows.filter(x=>`${x.name}${x.employeeNo||""}`.toLowerCase().includes(search.toLowerCase()));const current=sessions.find(x=>x.id===sessionId);const ended=current?dayjs().isAfter(current.endTime):false;const columns=[{title:"部门",dataIndex:["department","name"],width:150,render:(v:string)=><Tag color="blue">{v}</Tag>},{title:"员工",dataIndex:"name",width:130},{title:"工号",dataIndex:"employeeNo",width:100,render:(v?:string)=>v||"-"},{title:"过堂情况",width:180,render:(_:unknown,r:Emp)=><Select disabled={ended} value={r.record?.status||"pending"} style={{width:130}} options={Object.entries(labels).map(([value,label])=>({value,label}))} onChange={v=>void save(r.id,v,r.record?.remark)}/>},{title:"备注",render:(_:unknown,r:Emp)=><Input disabled={ended} defaultValue={r.record?.remark} placeholder="选填" onBlur={e=>{if(e.target.value!==(r.record?.remark||""))void save(r.id,r.record?.status||"pending",e.target.value)}}/>},{title:"状态",width:100,render:(_:unknown,r:Emp)=><Tag color={colors[r.record?.status||"pending"]}>{labels[r.record?.status||"pending"]}</Tag>}];
return <div><div className="page-toolbar"><div><h1>过堂记录</h1><p>创建过堂场次后，按部门记录员工过堂情况；截止后自动锁定。</p></div><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>创建过堂场次</Button></div><Card><Space wrap style={{marginBottom:16}}><Select value={sessionId} onChange={v=>{setSessionId(v);setDeptId(undefined)}} placeholder="请选择过堂场次" style={{width:280}} options={sessions.map(s=>({value:s.id,label:`${s.title}（${dayjs(s.startTime).format("MM-DD HH:mm")} 至 ${dayjs(s.endTime).format("MM-DD HH:mm")}）`}))}/><Select value={deptId} allowClear onClear={()=>setDeptId(undefined)} onChange={setDeptId} placeholder="全部人员" style={{width:170}} options={depts.map(d=>({value:d.id,label:d.name}))}/><Input.Search allowClear placeholder="搜索姓名或工号" onChange={e=>setSearch(e.target.value)} style={{width:200}}/>{current&&<><Tag color={ended?"red":"green"}>{ended?"已截止":"进行中"}</Tag><Button icon={<DownloadOutlined/>} href={`/api/export/passage-records?sessionId=${sessionId}`}>导出本场记录</Button></>}</Space><Table rowKey="id" dataSource={filtered} columns={columns} loading={loading} pagination={{pageSize:30}} scroll={{x:850}}/></Card><Drawer title="创建过堂场次" open={open} onClose={()=>setOpen(false)} extra={<Button type="primary" onClick={create}>创建</Button>} width={480}><Form form={form} layout="vertical"><Form.Item name="title" label="过堂标题" rules={[{required:true}]}><Input placeholder="例如：电视业务部 8 月产品过堂"/></Form.Item><Form.Item name="range" label="开始时间 / 截止时间" rules={[{required:true}]}><DatePicker.RangePicker showTime style={{width:"100%"}}/></Form.Item><Form.Item name="departmentIds" label="适用部门（不选即全部部门）"><Select mode="multiple" options={depts.map(d=>({value:d.id,label:d.name}))}/></Form.Item></Form></Drawer></div>}
