"use client";
import { useEffect, useState } from "react";
import { Button, Drawer, Form, Input, Select, DatePicker, Table, Tag, Progress, message, Popconfirm } from "antd";
import dayjs from "dayjs";
type Employee={id:number;name:string;department:{name:string}};
type Task={id:number;title:string;productLine:string;description?:string;recording?:string;materials?:string;dueDate?:string;assignments:Array<{id:number;employee:Employee;completedAt?:string;videoSeconds:number;videoDuration:number}>};
export default function Page(){const[tasks,setTasks]=useState<Task[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Task|null>(null),[selected,setSelected]=useState<React.Key[]>([]);const[form]=Form.useForm();
const load=async()=>{const[t,e]=await Promise.all([fetch('/api/learning-tasks').then(r=>r.json()),fetch('/api/employees?pageSize=500').then(r=>r.json())]);if(t.success)setTasks(t.data);if(e.success)setEmployees(e.data.items||e.data)};useEffect(()=>{void load()},[]);
const remove=async(ids:number[])=>{const r=await fetch('/api/learning-tasks',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});const d=await r.json();if(d.success){message.success('已删除');setSelected([]);load()}else message.error(d.message)};
const edit=(t:Task)=>{setEditing(t);form.setFieldsValue({...t,dueDate:t.dueDate?dayjs(t.dueDate):undefined,materials:JSON.parse(t.materials||'[]'),employeeIds:t.assignments.map(a=>a.employee.id)});setOpen(true)};
const submit=async()=>{const v=await form.validateFields();const r=await fetch('/api/learning-tasks',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...v,id:editing?.id,dueDate:v.dueDate?.toISOString(),materials:v.materials?.filter((x:{url?:string})=>x.url)||[]})});const d=await r.json();if(d.success){message.success(editing?'已保存修改':'已创建');setOpen(false);setEditing(null);form.resetFields();load()}else message.error(d.message)};
return <div><div style={{display:'flex',justifyContent:'space-between',marginBottom:20,flexWrap:'wrap',gap:12}}><div><h1 style={{margin:0}}>培训进度追踪</h1><p style={{color:'#82939e'}}>按显示器、电视分类管理补学任务和员工学习进度</p></div><div><Popconfirm title="删除后无法恢复，确定批量删除吗？" onConfirm={()=>remove(selected as number[])}><Button danger disabled={!selected.length} style={{marginRight:8}}>批量删除</Button></Popconfirm><Button type="primary" onClick={()=>{setEditing(null);form.resetFields();setOpen(true)}}>新建补学任务</Button></div></div><Table rowKey="id" dataSource={tasks} rowSelection={{selectedRowKeys:selected,onChange:setSelected}} expandable={{expandedRowRender:t=><Table rowKey="id" size="small" pagination={false} dataSource={t.assignments} columns={[{title:'员工',render:(_,a)=>a.employee.name},{title:'部门',render:(_,a)=>a.employee.department.name},{title:'进度',render:(_,a)=><Progress size="small" percent={a.completedAt?100:(a.videoDuration?Math.round(a.videoSeconds/a.videoDuration*100):0)}/>},{title:'状态',render:(_,a)=><Tag color={a.completedAt?'success':'processing'}>{a.completedAt?'已完成':'学习中/未开始'}</Tag>}]} />}} columns={[{title:'任务',dataIndex:'title'},{title:'分类',dataIndex:'productLine',render:v=><Tag>{v==='tv'?'电视':'显示器'}</Tag>},{title:'指定人数',render:(_,t)=>t.assignments.length},{title:'已完成',render:(_,t)=>`${t.assignments.filter(a=>a.completedAt).length}/${t.assignments.length}`},{title:'截止日期',dataIndex:'dueDate',render:v=>v?dayjs(v).format('YYYY-MM-DD'):'不限'},{title:'操作',render:(_,t)=><><Button type="link" onClick={()=>edit(t)}>编辑</Button><Popconfirm title="确定删除这条任务吗？" onConfirm={()=>remove([t.id])}><Button type="link" danger>删除</Button></Popconfirm></>}]} />
<Drawer open={open} onClose={()=>setOpen(false)} width={520} title={editing?'编辑补学任务':'新建补学任务'} extra={<Button type="primary" onClick={submit}>保存</Button>}><Form form={form} layout="vertical"><Form.Item name="title" label="培训主题" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="productLine" label="产品线" initialValue="display"><Select options={[{value:'display',label:'显示器'},{value:'tv',label:'电视'}]}/></Form.Item><Form.Item name="recording" label="录屏直链"><Input placeholder="请使用浏览器可直接播放的 MP4 链接"/></Form.Item><Form.Item name="dueDate" label="截止日期"><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item name="description" label="说明"><Input.TextArea/></Form.Item><Form.List name="materials">{(fields,{add,remove})=><><div>课件/一页纸</div>{fields.map(f=><div key={f.key} style={{display:'flex',gap:8,margin:'8px 0'}}><Form.Item name={[f.name,'name']} style={{margin:0,flex:1}}><Input placeholder="名称"/></Form.Item><Form.Item name={[f.name,'url']} style={{margin:0,flex:2}}><Input placeholder="文件链接"/></Form.Item><Button onClick={()=>remove(f.name)}>删除</Button></div>)}<Button onClick={()=>add({required:true})}>添加资料</Button></>}</Form.List><Form.Item name="employeeIds" label="指定员工" rules={[{required:true}]}><Select mode="multiple" options={employees.map(e=>({value:e.id,label:`${e.name}（${e.department.name}）`}))}/></Form.Item></Form></Drawer></div>}
