"use client";
import { useEffect, useState } from "react";
import { Button, Drawer, Form, Input, Select, DatePicker, Table, Tag, Progress, message } from "antd";
import dayjs from "dayjs";

type Employee = { id: number; name: string; department: { name: string } };
type Task = { id: number; title: string; productLine: string; dueDate?: string; assignments: Array<{ id: number; completedAt?: string; videoSeconds: number; videoDuration: number; viewedFiles: string; employee: Employee }> };
export default function LearningProgressAdminPage() {
 const [tasks,setTasks]=useState<Task[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[open,setOpen]=useState(false); const [form]=Form.useForm();
 const load=async()=>{ const [t,e]=await Promise.all([fetch('/api/learning-tasks').then(r=>r.json()),fetch('/api/employees?pageSize=500').then(r=>r.json())]); if(t.success)setTasks(t.data); if(e.success)setEmployees(e.data.items||e.data);}; useEffect(()=>{void load()},[]);
 const submit=async()=>{try{const v=await form.validateFields();const r=await fetch('/api/learning-tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...v,dueDate:v.dueDate?.toISOString(),materials:v.materials?.filter((m:{url?:string})=>m.url)||[]})});const d=await r.json();if(!d.success)throw new Error(d.message);message.success('学习任务已创建');setOpen(false);form.resetFields();load()}catch(e){if(e instanceof Error)message.error(e.message)}};
 return <div><div style={{display:'flex',justifyContent:'space-between',marginBottom:20}}><div><h1 style={{margin:0}}>培训进度追踪</h1><p style={{color:'#82939e'}}>按显示器、电视分类管理补学任务和员工学习进度</p></div><Button type="primary" onClick={()=>setOpen(true)}>新建补学任务</Button></div>
 <Table rowKey="id" dataSource={tasks} expandable={{expandedRowRender:t=><Table size="small" rowKey="id" pagination={false} dataSource={t.assignments} columns={[{title:'员工',render:(_,a)=>a.employee.name},{title:'部门',render:(_,a)=>a.employee.department.name},{title:'学习进度',render:(_,a)=>{const p=a.videoDuration?Math.round(a.videoSeconds/a.videoDuration*100):0;return <Progress percent={a.completedAt?100:p} size="small"/>}},{title:'状态',render:(_,a)=><Tag color={a.completedAt?'success':'processing'}>{a.completedAt?'已完成':'学习中/未开始'}</Tag>}]} />}} columns={[{title:'任务',dataIndex:'title'},{title:'分类',dataIndex:'productLine',render:v=><Tag color={v==='tv'?'purple':'blue'}>{v==='tv'?'电视':'显示器'}</Tag>},{title:'指定人数',render:(_,t)=>t.assignments.length},{title:'已完成',render:(_,t)=>`${t.assignments.filter(a=>a.completedAt).length}/${t.assignments.length}`},{title:'截止日期',dataIndex:'dueDate',render:v=>v?dayjs(v).format('YYYY-MM-DD'):'不限'}]} />
 <Drawer open={open} onClose={()=>setOpen(false)} title="新建补学任务" width={520} extra={<Button type="primary" onClick={submit}>保存并指定人员</Button>}><Form form={form} layout="vertical"><Form.Item name="title" label="培训主题" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="productLine" label="产品线" initialValue="display"><Select options={[{value:'display',label:'显示器'},{value:'tv',label:'电视'}]}/></Form.Item><Form.Item name="recording" label="培训录屏链接"><Input placeholder="视频播放链接"/></Form.Item><Form.Item name="dueDate" label="学习截止日期"><DatePicker style={{width:'100%'}}/></Form.Item><Form.List name="materials">{(fields,{add,remove})=><>{fields.map(f=><div key={f.key} style={{display:'flex',gap:8,marginBottom:8}}><Form.Item name={[f.name,'name']} style={{margin:0}}><Input placeholder="课件/一页纸名称"/></Form.Item><Form.Item name={[f.name,'url']} style={{margin:0}}><Input placeholder="链接"/></Form.Item><Button onClick={()=>remove(f.name)}>删除</Button></div>)}<Button onClick={()=>add({required:true})}>添加课件或一页纸</Button></>}</Form.List><Form.Item name="employeeIds" label="指定学习员工" rules={[{required:true}]}><Select mode="multiple" optionFilterProp="label" options={employees.map(e=>({value:e.id,label:`${e.name}（${e.department.name}）`}))}/></Form.Item></Form></Drawer></div>
}
